export { default as Space} from './Space'
export { default as Preview} from './Preview'
export { default as GameBoard} from './GameBoard'
export { default as Input} from './Input'
export { default as GameOver} from './GameOver'
export { default as About} from './About'
export { default as createTetrimo} from './TetrimoCreator'
